### ISSUE TITLE
Can't seem to connect

### ISSUE THREAD

**Issue by ItsNoted** [Maescool/docker-Cloudlog#1]
All 5 containers are starting in the stack but I am getting connection errors. All I did was modify the db password as stated before standing up the compose stack. I added the folders as stated on the readme. Not sure what it is. Redis ans MariaDB say ready for connections.

Let me know if you need specific logs or details.

This is the app container logs.

```
Making sure volumed directories have right perms
No config file, creating one based on template
Config file has been created.
No DB config file, creating one based on template
DB Config file has been created.
Wating for mysql to come up
done
```

I did change the web port to 8442 but I don't think that should matter?
`    ports:
      - 8442:80`

I even did a clean clone without changing anything but the env file names (removing sample) and adding my qrz info to the docker.app.env file. Got the same connection issues.

![image](https://user-images.githubusercontent.com/57927413/147860338-d061f1d0-471a-4d89-8782-43e15559ede9.png)

**Comment by Maescool** [comment]
Hi, 

thanks for noticing
It seems I need to add something to initialize the database (add the tables) correctly on first run.
I was testing this with an existing database, didn't do the setup from scratch.
Give me a bit to fix this, will update here when the fix is implemented.

**Comment by Maescool** [comment]
Hi,
Take a fresh pull, fixed auto install of database.
Also comment out the SESSION_DRIVER and SESSION_SAVE_PATH in docker.app.env file
Redis session storage seems to be somewhat broken in cloudlog

**Comment by ItsNoted** [comment]
Thanks. Working good so far!

**Comment by ItsNoted** [comment]
Nevermind. It's broken and I really don't feel like going through steps to fix it. Can't log a QSO. It just wont let me. Appreciate it anyway. I'll stick with NocoDB and spreadsheets for now.

**Comment by Maescool** [comment]
You need to add a station location under the profile, then it should be able to log.
I also recommend updating country files under admin.
