### ISSUE TITLE
Redis not used at all?

### ISSUE THREAD

**Issue by hirschnase** [Maescool/docker-Cloudlog#6]
Hello,

I was just wondering why the docker-compose file includes a Redis service. It seems like it is not used at all. When I exec into the container and run a INFO command, I can see that not a single key/value pair is stored in it.

Is there any other reason I can not think of?

**Comment by Wireheadbe** [comment]
You can omit it from the docker compose file, it's not being used, see commit c5c6464

**Comment by Maescool** [comment]
I was so used to add redis to projects, locally I used to to track my session, but since it's now removed in #11 we can use the other ways
