### ISSUE TITLE
New Install - QRZ logins not parsed

### ISSUE THREAD

**Issue by Wireheadbe** [Maescool/docker-Cloudlog#7]
Hi fellow OM, 

Seems like with the latest builds, the preloads script isn't parsing the QRZ username and password isn't added to the config.php. Something is going wrong with the sed inline replace :) 

Kind regards,
ON8AD

**Comment by Wireheadbe** [comment]
The preload contains a typo:
"QRZ_PASWORD" instead of "QRZ_PASSWORD" as given in the app env file.

Somehow, the environment variables where there (as verified by executing "export" in the docker container). However, the config wasn't getting those correct config variables for callbook / qrz username / qrz password. So I modified it temporary to this, and it seems to work. Dirty? Yes! Does it work? Yes! :) 
```
sed -ri "/callbook/c \$config[\'callbook\'] = \"${CALLBOOK}\"\;" ${CONFIGFILE}
sed -ri "/qrz_username/c \$config[\'qrz_username\'] = \"${QRZ_USERNAME}\"\;" ${CONFIGFILE}
sed -ri "/qrz_password/c \$config[\'qrz_password\'] = \"${QRZ_PASSWORD}\"\;" ${CONFIGFILE}
```

**Comment by Wireheadbe** [comment]
made a pull request with some updated sed statements

**Comment by Maescool** [comment]
Thank you for the fixes
73
ON1GPS
